### ISSUE TITLE
Add section on suppressing warnings

### ISSUE THREAD

**Issue by soniamitchell** [SBOHVM/RPiR#347]
Some of the students like to use `suppressWarnings()`.

I've also seen `suppressPackageStartupMessages()` and `library(dplyr, warn.conflicts = FALSE)`. Perhaps other variants.

I don't like suppressing warnings in the code like this (unexpected warnings would be invisible). I think they've learned some of this from the intro course. I might suggest teaching them how to hide warnings in rmarkdown (for reporting purposes).

**Comment by richardreeve** [comment]
I'm with you on this btw. I hate people suppressing warnings.

**Comment by soniamitchell** [comment]
One of the comments in the feedback was more integration with intro to R (where they’re taught to suppress warnings). I’d **really** like to coordinate somehow.

**Comment by richardreeve** [comment]
Yes, there has just been no time recently. Historically we used to coordinate, and several things that were in our course migrated to intro to R as a result...

**Comment by soniamitchell** [comment]
So we need to make time 👍 There were also bonus lectures for intro to R after RPiR finished.. maybe these can be included in the discussion.

**Comment by richardreeve** [comment]
Still need to talk to Intro to R, but now done.
